/**
 * Verdex — Knowledge Asset Exporters.
 *
 * Each exporter translates a KnowledgeAsset into a specific output format.
 * The internal KnowledgeAsset format is never tied to any external standard;
 * these exporters are the bridge.
 *
 * Exporters:
 *   - claudeSkill: SKILL.md with frontmatter (Agent Skills standard) + chapters
 *   - markdown:    Human-readable Markdown document
 *   - json:        Raw JSON of the asset
 *   - verdexNative: Verdex's own format (for internal reuse / lightweight client)
 */

import type { AssetExportResult, KnowledgeAsset } from "../../types/moa";
import { jsonToMarkdown } from "../jsonToMd";

/** Export to Claude Skill format (SKILL.md + chapters). */
export function exportClaudeSkill(asset: KnowledgeAsset): AssetExportResult {
  const skillName = slugify(asset.name);
  const header = [
    "---",
    `name: ${skillName}`,
    `description: ${asset.description}`,
    "---",
    "",
  ].join("\n");

  const body = [
    `# ${asset.name}`,
    "",
    asset.description,
    "",
    "## Consensus",
    asset.consensus || "(none)",
    "",
    "## Divergences",
    asset.divergences || "(none recorded)",
    "",
    "## Blind Spots",
    asset.blindspots || "(none recorded)",
    "",
    "## Verdict",
    asset.verdict || "(none)",
    "",
  ].join("\n");

  const extraFiles: { filename: string; content: string }[] = [];

  // If structured data exists, add as a chapter.
  if (asset.structuredData && Object.keys(asset.structuredData).length > 0) {
    extraFiles.push({
      filename: "structured-data.md",
      content: jsonToMarkdown(asset.structuredData, asset.name),
    });
  }

  // Source trace chapter.
  if (asset.sources.length > 0) {
    extraFiles.push({
      filename: "sources.md",
      content:
        "# Sources\n\n" +
        asset.sources.map((s, i) => `${i + 1}. ${s}`).join("\n"),
    });
  }

  return {
    format: "claude-skill",
    content: header + body,
    filename: "SKILL.md",
    extraFiles,
  };
}

/** Export to Markdown (human-readable). */
export function exportMarkdown(asset: KnowledgeAsset): AssetExportResult {
  const lines: string[] = [];
  lines.push(`# ${asset.name}`, "");
  lines.push(`> ${asset.description}`, "");

  if (asset.consensus) lines.push("## Consensus", asset.consensus, "");
  if (asset.divergences) lines.push("## Divergences", asset.divergences, "");
  if (asset.blindspots) lines.push("## Blind Spots", asset.blindspots, "");
  if (asset.verdict) lines.push("## Verdict", asset.verdict, "");

  if (asset.structuredData) {
    lines.push("## Structured Data", "");
    lines.push(jsonToMarkdown(asset.structuredData), "");
  }

  if (asset.sources.length > 0) {
    lines.push("## Sources", asset.sources.map((s) => `- ${s}`).join("\n"), "");
  }

  lines.push("---", `*Generated by Verdex · ${new Date(asset.createdAt).toISOString()}*`);

  return {
    format: "markdown",
    content: lines.join("\n"),
    filename: `${slugify(asset.name)}.md`,
  };
}

/** Export to JSON (machine-readable). */
export function exportJson(asset: KnowledgeAsset): AssetExportResult {
  return {
    format: "json",
    content: JSON.stringify(asset, null, 2),
    filename: `${slugify(asset.name)}.json`,
  };
}

/** Export to Verdex Native format (for internal reuse / lightweight client). */
export function exportVerdexNative(asset: KnowledgeAsset): AssetExportResult {
  // Verdex Native = JSON with a wrapper indicating it's a Verdex asset.
  const wrapper = {
    format: "verdex-native",
    version: "1.0",
    asset,
  };
  return {
    format: "verdex-native",
    content: JSON.stringify(wrapper, null, 2),
    filename: `${slugify(asset.name)}.verdex.json`,
  };
}

/** Main dispatch: export asset to the requested format. */
export function exportAsset(
  asset: KnowledgeAsset,
  format: AssetExportResult["format"]
): AssetExportResult {
  switch (format) {
    case "claude-skill":
      return exportClaudeSkill(asset);
    case "markdown":
      return exportMarkdown(asset);
    case "json":
      return exportJson(asset);
    case "verdex-native":
      return exportVerdexNative(asset);
    default:
      return exportMarkdown(asset);
  }
}

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

/** Convert a name to a slug suitable for filenames / skill names. */
function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .trim()
      .replace(/[^\w\u4e00-\u9fff\s-]/g, "")
      .replace(/\s+/g, "-")
      .slice(0, 50) || "untitled-asset"
  );
}
